/*
 * bl_updater.c — bootloader self-update from the application.
 *
 * Two entry points:
 *   bl_updater_run()                         — replace BL, reset (app stays)
 *   bl_updater_run_and_invalidate_app()      — replace BL, erase our own
 *                                              vector table, reset.
 *                                              For one-shot RECOVERY mode.
 *
 * The application carries an embedded copy of a bootloader binary (see
 * embedded_bootloader.h, generated by gen_embedded_bl.py for forward
 * updates or make_recovery_header.py for stock-revert builds).
 *
 * RISKS:
 *   - Power loss during BL erase or before BL write completes → bricked
 *     device, recoverable only with SWD.
 *   - bl_updater_run_and_invalidate_app() is one-shot: after it runs the
 *     calling application can no longer be booted by the BL (its vector
 *     table is gone). That's the point — the new BL falls through to DFU
 *     mode, ready for a fresh signed application push.
 *
 * Memory layout (nRF52840, S140 7.2.0):
 *     0x00000 - 0x01000   MBR
 *     0x01000 - 0x27000   SoftDevice
 *     0x27000 - 0xF3000   Application       <-- this code runs here
 *     0xF3000 - 0xFE000   Bootloader        <-- write target (44 KB / 11 pages)
 *     0xFE000 - 0xFF000   MBR params
 *     0xFF000 - 0x100000  Bootloader settings
 */

#include "bl_updater.h"
#include "embedded_bootloader.h"

#include <stdint.h>
#include <string.h>

#include "nrf.h"
#include "nrf_sdh.h"
#include "nrf_soc.h"
#include "nrf_delay.h"

#define BL_REGION_START    0x000F3000UL
#define BL_REGION_END      0x000FE000UL
#define BL_PAGE_SIZE       0x1000UL
#define BL_REGION_PAGES    ((BL_REGION_END - BL_REGION_START) / BL_PAGE_SIZE)
#define BL_REGION_BYTES    (BL_REGION_END - BL_REGION_START)

#define APP_REGION_START   0x00027000UL


/* ---- Inline NVMC ---- */

static inline void nvmc_wait_ready(void)
{
    while (NRF_NVMC->READY == NVMC_READY_READY_Busy) { /* spin */ }
}

static void nvmc_page_erase(uint32_t page_addr)
{
    nvmc_wait_ready();
    NRF_NVMC->CONFIG = (NVMC_CONFIG_WEN_Een << NVMC_CONFIG_WEN_Pos);
    nvmc_wait_ready();
    NRF_NVMC->ERASEPAGE = page_addr;
    nvmc_wait_ready();
    NRF_NVMC->CONFIG = (NVMC_CONFIG_WEN_Ren << NVMC_CONFIG_WEN_Pos);
    nvmc_wait_ready();
}

static void nvmc_write_bytes(uint32_t dst, const uint8_t *src, uint32_t len)
{
    nvmc_wait_ready();
    NRF_NVMC->CONFIG = (NVMC_CONFIG_WEN_Wen << NVMC_CONFIG_WEN_Pos);
    nvmc_wait_ready();

    uint32_t remaining = len;
    while (remaining >= 4) {
        uint32_t word;
        memcpy(&word, src, 4);
        *(volatile uint32_t *)dst = word;
        nvmc_wait_ready();
        dst       += 4;
        src       += 4;
        remaining -= 4;
    }
    if (remaining != 0) {
        uint32_t word = 0xFFFFFFFFu;
        memcpy(&word, src, remaining);
        *(volatile uint32_t *)dst = word;
        nvmc_wait_ready();
    }

    NRF_NVMC->CONFIG = (NVMC_CONFIG_WEN_Ren << NVMC_CONFIG_WEN_Pos);
    nvmc_wait_ready();
}


/* CRC32 (zlib polynomial 0xEDB88320, init 0xFFFFFFFF, final XOR). */
static uint32_t crc32_compute(const uint8_t *p, uint32_t len)
{
    uint32_t crc = 0xFFFFFFFFu;
    for (uint32_t i = 0; i < len; i++) {
        crc ^= p[i];
        for (int b = 0; b < 8; b++) {
            crc = (crc >> 1) ^ (0xEDB88320u & -(int32_t)(crc & 1u));
        }
    }
    return ~crc;
}


bl_updater_status_t bl_updater_validate(void)
{
    if (EMBEDDED_BOOTLOADER_BIN_SIZE == 0u) {
        return BL_UPDATER_ERR_EMPTY;
    }
    if (EMBEDDED_BOOTLOADER_BIN_SIZE > BL_REGION_BYTES) {
        return BL_UPDATER_ERR_TOO_LARGE;
    }
    if (crc32_compute(EMBEDDED_BOOTLOADER_BIN, EMBEDDED_BOOTLOADER_BIN_SIZE)
        != EMBEDDED_BOOTLOADER_BIN_CRC32) {
        return BL_UPDATER_ERR_CRC;
    }
    return BL_UPDATER_OK;
}


/* Internal — disables SoftDevice and erases+writes the BL region.
 * Caller decides what to do next (reset, or self-destruct first). */
static bl_updater_status_t bl_updater_flash_bl(void)
{
    bl_updater_status_t st = bl_updater_validate();
    if (st != BL_UPDATER_OK) {
        return st;
    }

    if (nrf_sdh_is_enabled()) {
        ret_code_t err = nrf_sdh_disable_request();
        if (err != NRF_SUCCESS) {
            return BL_UPDATER_ERR_SD_DISABLE;
        }
        while (nrf_sdh_is_enabled()) { /* observers tear down */ }
    }

    __disable_irq();

    for (uint32_t i = 0; i < BL_REGION_PAGES; i++) {
        nvmc_page_erase(BL_REGION_START + i * BL_PAGE_SIZE);
    }

    nvmc_write_bytes(BL_REGION_START,
                     EMBEDDED_BOOTLOADER_BIN,
                     EMBEDDED_BOOTLOADER_BIN_SIZE);

    return BL_UPDATER_OK;
}


bl_updater_status_t bl_updater_run(void)
{
    bl_updater_status_t st = bl_updater_flash_bl();
    if (st != BL_UPDATER_OK) {
        return st;
    }

    nrf_delay_ms(50);
    NVIC_SystemReset();
    return BL_UPDATER_OK; /* unreached */
}


/* One-shot recovery: write the new bootloader, then make ourselves
 * un-bootable by clobbering the application's vector table. The new
 * (stock) BL boots up, fails to validate the app, and falls through to
 * DFU mode automatically — exactly the state the user wants for pushing
 * the stock signed application via flash-dfu-app.sh.
 *
 * The self-destruct happens AFTER the BL write completes successfully,
 * so a power loss between the two leaves the device in a consistent
 * state: new BL in place, our (recovery) app still valid. On next boot
 * we run again, detect the BL matches, and complete the self-destruct.
 * Either way, the user can recover. */
bl_updater_status_t bl_updater_run_and_invalidate_app(void)
{
    bl_updater_status_t st = bl_updater_flash_bl();
    if (st != BL_UPDATER_OK) {
        return st;
    }

    /* Erase the application's first page — the one containing our own
     * vector table at APP_REGION_START. After this the BL's startup
     * CRC/validity check on the app will fail and it will enter DFU
     * mode instead of trying to boot us. */
    nvmc_page_erase(APP_REGION_START);

    nrf_delay_ms(50);
    NVIC_SystemReset();
    return BL_UPDATER_OK; /* unreached */
}
