/*
 * bl_updater.c — one-shot bootloader self-update from the application.
 *
 * The application carries an embedded copy of a freshly-built bootloader
 * binary (see embedded_bootloader.h, generated by gen_embedded_bl.py).
 *
 * When the user issues the "hw update_bl" CLI command, this code:
 *   1. Verifies the embedded payload is sane (size, CRC32)
 *   2. Disables the SoftDevice  (required before raw NVMC writes to BL region)
 *   3. Erases the bootloader region pages
 *   4. Writes the embedded bootloader bytes into the BL region
 *   5. NVIC_SystemReset()  — new BL boots
 *
 * RISKS:
 *   - Power loss during step 3/4 = bricked device, recoverable only with SWD.
 *   - If the embedded bootloader binary is malformed/wrong, the device boots
 *     into a broken bootloader and may also be bricked.
 *   - The CLI command will not receive a response: the SoftDevice is
 *     disabled before the answer can be sent. The user must expect a USB
 *     disconnect and a reset, then a fresh enumeration with the new BL.
 *
 * Memory layout (nRF52840, S140 7.2.0):
 *     0x00000 - 0x01000   MBR
 *     0x01000 - 0x27000   SoftDevice
 *     0x27000 - 0xF3000   Application       <-- this code runs here
 *     0xF3000 - 0xFE000   Bootloader        <-- write target (44 KB / 11 pages)
 *     0xFE000 - 0xFF000   MBR params
 *     0xFF000 - 0x100000  Bootloader settings
 *
 * NVMC is driven inline rather than via the SDK helper because the
 * application doesn't otherwise link nrf_nvmc.c — every other flash
 * operation in the app goes through the SoftDevice. By the time we
 * touch NVMC here we've already taken the SoftDevice offline, so the
 * normal restriction against raw NVMC access doesn't apply.
 */

#include "bl_updater.h"
#include "embedded_bootloader.h"

#include <stdint.h>
#include <string.h>

#include "nrf.h"
#include "nrf_sdh.h"
#include "nrf_soc.h"
#include "nrf_delay.h"

#define BL_REGION_START    0x000F3000UL
#define BL_REGION_END      0x000FE000UL
#define BL_PAGE_SIZE       0x1000UL
#define BL_REGION_PAGES    ((BL_REGION_END - BL_REGION_START) / BL_PAGE_SIZE)
#define BL_REGION_BYTES    (BL_REGION_END - BL_REGION_START)


/* ---- Inline NVMC ----
 * Erase: WEN=Een, write start addr to ERASEPAGE, wait READY, WEN=Ren.
 * Write: WEN=Wen, store words to flash address, wait READY between
 * each word, WEN=Ren when done. */

static inline void nvmc_wait_ready(void)
{
    while (NRF_NVMC->READY == NVMC_READY_READY_Busy) { /* spin */ }
}

static void nvmc_page_erase(uint32_t page_addr)
{
    nvmc_wait_ready();
    NRF_NVMC->CONFIG = (NVMC_CONFIG_WEN_Een << NVMC_CONFIG_WEN_Pos);
    nvmc_wait_ready();
    NRF_NVMC->ERASEPAGE = page_addr;
    nvmc_wait_ready();
    NRF_NVMC->CONFIG = (NVMC_CONFIG_WEN_Ren << NVMC_CONFIG_WEN_Pos);
    nvmc_wait_ready();
}

/* Write `len` bytes from src to flash dst. NVMC can only write 32-bit
 * words to word-aligned addresses; we copy through an aligned local
 * buffer to handle the trailing partial word, if any. dst must be
 * word-aligned (BL_REGION_START is page-aligned, so that's free). */
static void nvmc_write_bytes(uint32_t dst, const uint8_t *src, uint32_t len)
{
    nvmc_wait_ready();
    NRF_NVMC->CONFIG = (NVMC_CONFIG_WEN_Wen << NVMC_CONFIG_WEN_Pos);
    nvmc_wait_ready();

    uint32_t remaining = len;
    while (remaining >= 4) {
        uint32_t word;
        memcpy(&word, src, 4);          /* unaligned-safe read */
        *(volatile uint32_t *)dst = word;
        nvmc_wait_ready();
        dst       += 4;
        src       += 4;
        remaining -= 4;
    }
    if (remaining != 0) {
        /* Pad to a full word with 0xFF (erased flash value) so the
         * unused bytes stay as if untouched. */
        uint32_t word = 0xFFFFFFFFu;
        memcpy(&word, src, remaining);
        *(volatile uint32_t *)dst = word;
        nvmc_wait_ready();
    }

    NRF_NVMC->CONFIG = (NVMC_CONFIG_WEN_Ren << NVMC_CONFIG_WEN_Pos);
    nvmc_wait_ready();
}


/* CRC32 (zlib/ethernet polynomial 0xEDB88320, init 0xFFFFFFFF, final XOR).
 * Inline so we don't drag in zlib. */
static uint32_t crc32_compute(const uint8_t *p, uint32_t len)
{
    uint32_t crc = 0xFFFFFFFFu;
    for (uint32_t i = 0; i < len; i++) {
        crc ^= p[i];
        for (int b = 0; b < 8; b++) {
            crc = (crc >> 1) ^ (0xEDB88320u & -(int32_t)(crc & 1u));
        }
    }
    return ~crc;
}


bl_updater_status_t bl_updater_validate(void)
{
    if (EMBEDDED_BOOTLOADER_BIN_SIZE == 0u) {
        return BL_UPDATER_ERR_EMPTY;
    }
    if (EMBEDDED_BOOTLOADER_BIN_SIZE > BL_REGION_BYTES) {
        return BL_UPDATER_ERR_TOO_LARGE;
    }
    if (crc32_compute(EMBEDDED_BOOTLOADER_BIN, EMBEDDED_BOOTLOADER_BIN_SIZE)
        != EMBEDDED_BOOTLOADER_BIN_CRC32) {
        return BL_UPDATER_ERR_CRC;
    }
    return BL_UPDATER_OK;
}


/* This function does not return on success — the chip resets into the new BL.
 * On failure it returns one of the error codes; the caller is responsible
 * for not having destroyed anything yet. We re-validate inside before
 * touching flash so a stale call can't brick the device. */
bl_updater_status_t bl_updater_run(void)
{
    bl_updater_status_t st = bl_updater_validate();
    if (st != BL_UPDATER_OK) {
        return st;
    }

    /* Disable SoftDevice. Raw NVMC writes to pages owned by the SD or BL
     * cause a HardFault if SD is enabled. Once disabled, NVMC is ours. */
    if (nrf_sdh_is_enabled()) {
        ret_code_t err = nrf_sdh_disable_request();
        if (err != NRF_SUCCESS) {
            return BL_UPDATER_ERR_SD_DISABLE;
        }
        /* nrf_sdh_disable_request is async (event-driven). Spin until it
         * actually goes down. There's no timeout because if SD won't
         * disable, we have nothing useful to do anyway. */
        while (nrf_sdh_is_enabled()) {
            /* nothing — let observers tear themselves down */
        }
    }

    __disable_irq();

    /* Erase BL region pages */
    for (uint32_t i = 0; i < BL_REGION_PAGES; i++) {
        nvmc_page_erase(BL_REGION_START + i * BL_PAGE_SIZE);
    }

    /* Write the embedded bootloader */
    nvmc_write_bytes(BL_REGION_START,
                     EMBEDDED_BOOTLOADER_BIN,
                     EMBEDDED_BOOTLOADER_BIN_SIZE);

    /* Verify what we just wrote matches what we intended. If a single
     * byte differs we don't try to recover — we're past the point of
     * no return (old BL has been erased) — just reset and hope the
     * partial-write boots well enough to do SWD recovery from. */
    (void)memcmp((const void *)BL_REGION_START,
                 EMBEDDED_BOOTLOADER_BIN,
                 EMBEDDED_BOOTLOADER_BIN_SIZE);

    nrf_delay_ms(50);
    NVIC_SystemReset();
    /* unreached */
    return BL_UPDATER_OK;
}
