#!/usr/bin/env python3
"""
make_recovery_header.py — extract the stock bootloader from an upstream
ChameleonUltra release zip and emit embedded_bootloader.h for use in a
RECOVERY-mode application build.

The upstream `ultra-dfu-full.zip` contains:
    sd_bl.bin           SoftDevice + Bootloader, concatenated
    sd_bl.dat           Nordic init packet for the BL+SD image
    application.bin     Stock application
    application.dat     Nordic init packet for the application
    manifest.json       Tells us the SD/BL split point inside sd_bl.bin

The manifest publishes `sd_size` and `bl_size`. The bootloader bytes live
at offset [sd_size, sd_size+bl_size) inside sd_bl.bin. We slice them out,
sanity-check the vector table (initial SP, reset handler must point into
the BL region 0xF3000-0xFE000), compute CRC32, and emit the C header
that bl_updater.c expects.

Usage:
    ./make_recovery_header.py ultra-dfu-full.zip \\
        firmware/application/src/embedded_bootloader.h
"""
import os
import sys
import json
import zlib
import struct
import zipfile


BL_REGION_START = 0x000F3000
BL_REGION_END   = 0x000FE000
BL_REGION_BYTES = BL_REGION_END - BL_REGION_START


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)

    zip_path, out_path = sys.argv[1], sys.argv[2]

    if not zipfile.is_zipfile(zip_path):
        print(f"error: {zip_path} is not a zip archive", file=sys.stderr)
        sys.exit(1)

    with zipfile.ZipFile(zip_path) as zf:
        names = set(zf.namelist())
        for required in ("manifest.json", "sd_bl.bin"):
            if required not in names:
                print(
                    f"error: {zip_path} is missing {required} — "
                    "this doesn't look like a Chameleon DFU package",
                    file=sys.stderr,
                )
                sys.exit(1)

        with zf.open("manifest.json") as mf:
            manifest = json.load(mf)

        sd_bl_meta = manifest["manifest"]["softdevice_bootloader"]
        sd_size = sd_bl_meta["info_read_only_metadata"]["sd_size"]
        bl_size = sd_bl_meta["info_read_only_metadata"]["bl_size"]

        print(f"manifest: SD = {sd_size} bytes, BL = {bl_size} bytes")

        if bl_size > BL_REGION_BYTES:
            print(
                f"error: stock BL is {bl_size} bytes but BL region is only "
                f"{BL_REGION_BYTES} bytes — refusing to generate",
                file=sys.stderr,
            )
            sys.exit(1)

        with zf.open("sd_bl.bin") as f:
            sd_bl = f.read()

    if len(sd_bl) < sd_size + bl_size:
        print(
            f"error: sd_bl.bin is {len(sd_bl)} bytes but manifest expects "
            f"at least {sd_size + bl_size}",
            file=sys.stderr,
        )
        sys.exit(1)

    bl_bytes = sd_bl[sd_size:sd_size + bl_size]

    # Sanity-check the vector table head.
    sp, reset, *_ = struct.unpack_from("<II", bl_bytes, 0)
    if not (reset & 1):
        print(
            f"warning: reset handler 0x{reset:08X} doesn't have thumb bit "
            "set — this is suspicious for an ARM Cortex-M image",
            file=sys.stderr,
        )
    reset_addr = reset & ~1
    if not (BL_REGION_START <= reset_addr < BL_REGION_END):
        print(
            f"error: reset handler 0x{reset_addr:08X} is outside the BL "
            f"region [0x{BL_REGION_START:X}, 0x{BL_REGION_END:X}) — "
            "this doesn't look like a Chameleon Ultra bootloader",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"  initial SP    : 0x{sp:08X}")
    print(f"  reset handler : 0x{reset_addr:08X}  (BL region — OK)")

    crc = zlib.crc32(bl_bytes) & 0xFFFFFFFF

    with open(out_path, "w") as f:
        f.write(
            "/* Auto-generated by make_recovery_header.py — do not edit. */\n"
            "/* Source: upstream ultra-dfu-full.zip (stock bootloader). */\n"
            f"/* BL region [0x{BL_REGION_START:08X}, 0x{BL_REGION_END:08X}) */\n"
        )
        f.write("#ifndef EMBEDDED_BOOTLOADER_H\n")
        f.write("#define EMBEDDED_BOOTLOADER_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define EMBEDDED_BOOTLOADER_BIN_SIZE  {len(bl_bytes)}u\n")
        f.write(f"#define EMBEDDED_BOOTLOADER_BIN_CRC32 0x{crc:08X}u\n\n")
        f.write("static const uint8_t EMBEDDED_BOOTLOADER_BIN[EMBEDDED_BOOTLOADER_BIN_SIZE]\n")
        f.write("    __attribute__((aligned(4))) = {\n")
        for i in range(0, len(bl_bytes), 16):
            chunk = bl_bytes[i:i + 16]
            hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {hex_bytes},\n")
        f.write("};\n\n")
        f.write("#endif /* EMBEDDED_BOOTLOADER_H */\n")

    print(f"\nWrote {out_path}")
    print(f"  size  : {len(bl_bytes)} bytes")
    print(f"  CRC32 : 0x{crc:08X}")
    print()
    print("Next steps to build a recovery UF2:")
    print("  1. Set RECOVERY_MODE=1 in firmware/application/Makefile, or")
    print("     export RECOVERY_MODE=1 before running build.sh")
    print("  2. cd firmware && ./build.sh")
    print("  3. tools/uf2conv.py objects/application.hex -o recovery.uf2")
    print()
    print("End user instructions:")
    print("  1. Enter UF2 DFU mode (cold-boot + hold B + plug)")
    print("  2. Drag recovery.uf2 onto CHAMELEON drive")
    print("  3. Wait ~2 seconds for the LEDs to indicate completion")
    print("  4. Stock bootloader will boot into DFU mode automatically")
    print("  5. Push stock application: ./flash-dfu-app.sh")


if __name__ == "__main__":
    main()
